#pragma once

namespace mission {

enum class MissionEvent {
    LOAD_MISSION,
    PREFLIGHT_OK,
    PREFLIGHT_FAIL,
    VEHICLE_ARMED,

    OPERATOR_ARM_CONFIRM,
    OPERATOR_AUTO_CONFIRM,   
    OPERATOR_ABORT,

    TRANSIT_REACHED,
    TARGET_DETECTED,

    OPERATOR_ENGAGE_CONFIRM,
    ENGAGEMENT_COMPLETE,
    ENGAGEMENT_FAILED,
    BDA_EVALUATED,

    MISSION_COMPLETE,
    RTB_COMPLETE,
    SYSTEM_FAILURE
};
}
